version: "3.7"
services:
  app:
    build: ./build
    restart: always
    ports:
    - ${KOOL_APP_PORT:-80}:80
    environment:
      ASUSER: ${KOOL_ASUSER:-0}
      UID: ${UID:-0}
      PHP_FPM_REQUEST_TERMINATE_TIMEOUT: "1800s"
      NGINX_FASTCGI_READ_TIMEOUT: "1800"
      PHP_MAX_EXECUTION_TIME: "3600"
    volumes:
    - .:/app:delegated
    networks:
    - kool_local
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3333:3306'
    expose:
      - '3333'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - kool_local
# Names our volume
volumes:
  cache: null
  my-db: null
networks:
  kool_local: null
  kool_global:
    external: true
    name: ${KOOL_GLOBAL_NETWORK:-kool_global}
